name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.15'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[examples] -v

      - name: Run Python scripts in examples
        run: |
          python examples/pitcher.py
          python examples/robotiq_hand_grasp.py
          python examples/primitive.py
